// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE

import * as Emotion from "bs-emotion/lib/es6/src/Emotion.bs.js";

var wrap = Emotion.css(undefined, /* :: */[
      Emotion.label("wrap"),
      /* :: */[
        Emotion.padding(/* `px */[
              25096,
              40
            ]),
        /* [] */0
      ]
    ]);

var dropdowns = Emotion.css(undefined, /* :: */[
      Emotion.label("dropdowns"),
      /* :: */[
        Emotion.position(/* fixed */10615156),
        /* :: */[
          Emotion.right(/* `px */[
                25096,
                40
              ]),
          /* :: */[
            Emotion.top(/* `px */[
                  25096,
                  40
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var translate = Emotion.css(undefined, /* :: */[
      Emotion.label("translate"),
      /* :: */[
        Emotion.alignItems(/* center */98248149),
        /* :: */[
          Emotion.display(/* flex */-1010954439),
          /* :: */[
            Emotion.flexDirection(/* column */-963948842),
            /* :: */[
              Emotion.height(/* `calc */[
                    -1044768619,
                    /* tuple */[
                      /* sub */5745024,
                      /* `vh */[
                        26418,
                        100.0
                      ],
                      /* `px */[
                        25096,
                        80
                      ]
                    ]
                  ]),
              /* :: */[
                Emotion.justifyContent(/* center */98248149),
                /* :: */[
                  Emotion.listStyleType(/* none */-922086728),
                  /* :: */[
                    Emotion.margin(/* `px */[
                          25096,
                          0
                        ]),
                    /* :: */[
                      Emotion.padding(/* `px */[
                            25096,
                            0
                          ]),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var spoken = Emotion.css(undefined, /* :: */[
      Emotion.label("spoken"),
      /* :: */[
        Emotion.color(/* `hsl */[
              5197569,
              /* tuple */[
                175,
                34,
                10
              ]
            ]),
        /* :: */[
          Emotion.fontSize(/* `px */[
                25096,
                21
              ]),
          /* :: */[
            Emotion.fontWeight(600),
            /* :: */[
              Emotion.marginTop(/* `px */[
                    25096,
                    10
                  ]),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var response = Emotion.css(undefined, /* :: */[
      Emotion.label("response"),
      /* :: */[
        Emotion.color(/* `hsl */[
              5197569,
              /* tuple */[
                175,
                34,
                50
              ]
            ]),
        /* :: */[
          Emotion.fontSize(/* `px */[
                25096,
                100
              ]),
          /* :: */[
            Emotion.fontWeight(700),
            /* [] */0
          ]
        ]
      ]
    ]);

export {
  wrap ,
  dropdowns ,
  translate ,
  spoken ,
  response ,
  
}
/* wrap Not a pure module */
